fixtures:
  repositories:
    stdlib:
      repo: git://github.com/puppetlabs/puppetlabs-stdlib.git
      ref: "4.12.0"
    concat: git://github.com/puppetlabs/puppetlabs-concat.git
  symlinks:
    autofs: "#{source_dir}"
