---
language: ruby
bundler_args: --without development system_tests
before_install: rm Gemfile.lock || true
sudo: false
rvm:
  - 2.1.5
  - 2.2
  - 2.3.1
script: bundle exec rake test
env:
  - PUPPET_GEM_VERSION="~> 4.0"
  - PUPPET_GIT_URL="https://github.com/puppetlabs/puppet.git"
matrix:
  fast_finish: true
  include:
    - rvm: 2.3.1
      env: PUPPET_INSTALL_TYPE=agent BEAKER_debug=true BEAKER_set=docker/ubuntu14.04
      bundler_args: --without development
      script: bundle exec rake acceptance
      services: docker
      sudo: required
    - rvm: 2.3.1
      env: PUPPET_INSTALL_TYPE=agent BEAKER_debug=true BEAKER_set=docker/centos-7
      bundler_args: --without development
      script: bundle exec rake acceptance
      services: docker
      sudo: required
    - rvm: 2.3.1
      env: PUPPET_INSTALL_TYPE=agent BEAKER_debug=true BEAKER_set=docker/ubuntu16.04
      bundler_args: --without development
      script: bundle exec rake acceptance
      services: docker
      sudo: required
    - rvm: 2.3.1
      env: PUPPET_INSTALL_TYPE=agent BEAKER_debug=true BEAKER_set=docker/debian-7
      bundler_args: --without development
      script: bundle exec rake acceptance
      services: docker
      sudo: required
    - rvm: 2.3.1
      env: PUPPET_INSTALL_TYPE=agent BEAKER_debug=true BEAKER_set=docker/debian-8
      bundler_args: --without development
      script: bundle exec rake acceptance
      services: docker
      sudo: required
    - rvm: 2.3.1
      env: PUPPET_INSTALL_TYPE=agent BEAKER_debug=true BEAKER_set=docker/centos-6
      bundler_args: --without development
      script: bundle exec rake acceptance
      services: docker
      sudo: required
  allow_failures:
    - env: PUPPET_GIT_URL="https://github.com/puppetlabs/puppet.git"
notifications:
  email: false
